### ISSUE TITLE
Wallets created online don't show in client, wallets created in client: "This is an older BitGo wallet"

### ISSUE THREAD

**Issue by BitBargain** [BitGo/bitgo-cli#27]
I'm just starting out getting to know BitGo and I do apologise if the question is answered somewhere that I missed.

The wallets I create online don't show up in the client (currently I have 3)

> [bitgo @ DepoTest]Ƀ wallets
> Wallets:
? >> 0  33JLNuLrSGeCeqmpmPB3pHcsL3DGiUpvy2           0 BTC  DepoTest

The wallet I create in the client shows up on the web, but I get the warning

> This is an older BitGo wallet. Follow these instructions to upgrade to the newest, most feature-rich BitGo wallet. 

How do I create a "feature rich wallet" and be able to manage it from cli? Thanks in advance for your help.

**Comment by kkennis** [comment]
Hi @BitBargain,

This tool is deprecated, which is why you are encountering these errors. Online-created wallets use our V2 wallet protocol, and this tool uses our V1 protocol, which is the source of both of these issues.

Please use https://github.com/BitGo/bitgo-cli-v2 to create new V2 wallets which can be managed both online and in the CLI.
